// ════════════════════════════════════════════════════════════════
//  AXE — PROGRAMME 24 SEMAINES · 100 % BMX RACE
//  Objectif physique : LE START et la PREMIÈRE LIGNE.
//  → explosivité, force, puissance. Tout au poids du corps (+ vélo).
//
//  Structure de chaque semaine :
//   { s, phase, titre,
//     mental:{titre, pourquoi, consigne, declencheur},
//     lundi:{titre, focus, exos12:[...], exos18:[...], conseil},
//     jeudi:{...} }
//
//   exos12 = version 12-15 ans (volumes réduits, technique d'abord)
//   exos18 = version 15-18 ans (volumes et intensité plus élevés)
//   → programme.html affiche UNIQUEMENT la tranche d'âge du pilote.
//
//  4 blocs de 6 semaines :
//   BLOC 1 (1-6)  : Fondations — gainage, posture de start, poussée
//   BLOC 2 (7-12) : Construction — explosivité du start, premiers pedal strokes
//   BLOC 3 (13-18): Puissance — force max des jambes, vitesse de jambes
//   BLOC 4 (19-24): Performance — start + première ligne, pic de forme
// ════════════════════════════════════════════════════════════════

const SEMAINES = [
// ─────────────────────────── BLOC 1 · FONDATIONS ───────────────────────────
{ s:1, phase:"Fondations", titre:"Poser le socle",
  mental:{ titre:"Le scan de tension en 60 secondes",
    pourquoi:"Avant de gérer ton stress dans la grille de départ, il faut SENTIR où il se loge dans ton corps. Beaucoup de pilotes ne savent même pas qu'ils serrent les épaules ou la mâchoire avant le portillon — et ça leur coûte leur start.",
    consigne:"Une fois par jour, assieds-toi 60 secondes. Pars des pieds et remonte lentement : pieds, mollets, cuisses, ventre, mains, épaules, mâchoire. À chaque zone, demande-toi : « est-ce tendu ? » Si oui, contracte fort 5 secondes, puis relâche d'un coup. Note mentalement tes 2 zones les plus tendues.",
    declencheur:"En 7 jours, tu vas repérer TES zones de tension perso. C'est la première fois que tu prends le contrôle de quelque chose que tu subissais dans la grille." },
  lundi:{ titre:"Gainage : le tronc du start", focus:"Construire le ventre qui transfère ta poussée dans le vélo",
    exos12:["Planche sur les coudes : 4 × 20 secondes (45 s de repos)","Planche sur le côté : 3 × 15 secondes par côté","Superman au sol (bras et jambes décollés) : 3 × 10","Ventre creux dos au sol, jambes en l'air (hollow) : 3 × 15 secondes"],
    exos18:["Planche sur les coudes : 4 × 40 secondes (45 s de repos)","Planche sur le côté : 3 × 30 secondes par côté","Superman au sol (bras et jambes décollés) : 3 × 15","Ventre creux dos au sol, jambes en l'air (hollow) : 3 × 30 secondes"],
    conseil:"Le gainage n'est pas un exercice d'abdos pour faire joli. C'est ce qui empêche ta force de se perdre quand tu écrases les pédales au portillon. Reste dur comme une planche, sans creuser le bas du dos." },
  jeudi:{ titre:"La position de start", focus:"Apprendre la posture d'attaque sur le vélo",
    exos12:["Position de départ tenue au sol (genoux pliés, buste penché en avant, bras prêts à tirer) : 5 × 15 secondes","Demi-squat tenu en position basse : 4 × 15 secondes","Pompes lentes (3 s pour descendre) : 4 × 5","Chaise contre le mur : 3 × 20 secondes"],
    exos18:["Position de départ tenue au sol (genoux pliés, buste penché en avant, bras prêts à tirer) : 5 × 25 secondes","Demi-squat tenu en position basse : 5 × 25 secondes","Pompes lentes (3 s pour descendre) : 4 × 8","Chaise contre le mur : 3 × 40 secondes"],
    conseil:"Reproduis ta position au portillon : poids vers l'avant, bras fléchis prêts à tirer le guidon, regard loin sur la butte. Ton corps mémorise cette posture pour qu'elle devienne un réflexe le jour de la course." } },

{ s:2, phase:"Fondations", titre:"Respirer pour performer",
  mental:{ titre:"La cohérence cardiaque 5-5",
    pourquoi:"Ton rythme cardiaque pilote ton stress. En respirant à un rythme précis, tu envoies à ton cerveau le signal « tout va bien » — même quand tu es dans la grille avec 7 autres pilotes. C'est physiologique, pas psychologique : ça marche à tous les coups.",
    consigne:"3 fois par jour : inspire 5 secondes par le nez, expire 5 secondes par la bouche. Pendant 5 minutes. Matin, midi, et surtout le soir avant de dormir. Compte dans ta tête.",
    declencheur:"Tu vas mieux dormir la veille des courses dès la 2e semaine. Ton corps apprend à se calmer sur commande, même quand l'enjeu monte." },
  lundi:{ titre:"Gainage en mouvement", focus:"Le tronc qui te stabilise pendant la poussée",
    exos12:["Planche avec touches d'épaule (main qui touche l'épaule opposée) : 4 × 12 touches","Grimpeur lent au sol (genou vers le coude) : 4 × 20 secondes","Dead bug (bras et jambe opposés qui descendent) : 3 × 10","Planche latérale avec petite rotation : 3 × 8 par côté"],
    exos18:["Planche avec touches d'épaule : 4 × 20 touches","Grimpeur lent au sol : 4 × 30 secondes","Dead bug : 3 × 12","Planche latérale avec rotation : 3 × 10 par côté"],
    conseil:"En course, ton tronc travaille en permanence pour te garder stable quand tu pousses fort sur les pédales. On entraîne un gainage qui résiste ET qui bouge." },
  jeudi:{ titre:"Force des jambes", focus:"La base de poussée du start",
    exos12:["Squats (flexions de jambes) au poids du corps : 4 × 12","Fentes en marchant : 3 × 8 par jambe","Montées sur une marche ou un banc : 3 × 10 par jambe","Mollets debout (montées sur la pointe des pieds) : 4 × 15"],
    exos18:["Squats au poids du corps : 4 × 18","Fentes en marchant : 3 × 12 par jambe","Montées sur une marche ou un banc : 3 × 14 par jambe","Mollets debout : 4 × 25"],
    conseil:"Descends lentement (3 secondes), remonte le plus vite possible. C'est ce contraste lent-rapide qui construit la puissance dont tu as besoin pour arracher le portillon." } },

{ s:3, phase:"Fondations", titre:"Ancrer la concentration",
  mental:{ titre:"Le mot-ancre",
    pourquoi:"Quand ta tête part dans tous les sens dans la grille, tu as besoin d'un point de retour immédiat. Un seul mot, répété, qui ramène toute ton attention sur le portillon.",
    consigne:"Choisis UN mot qui te met en mode attaque : « explose », « maintenant », « pousse », « devant »… À chaque séance physique cette semaine, répète-le dans ta tête au début de chaque série. Tu crées un lien entre ce mot et l'action.",
    declencheur:"À force de répétition, ce mot deviendra ton interrupteur de concentration. Dans la grille, tu le diras et ton focus reviendra net sur la porte qui va tomber." },
  lundi:{ titre:"Gainage anti-déséquilibre", focus:"Rester solide quand une force te pousse",
    exos12:["Planche sur les coudes : 4 × 30 secondes","Serviette tendue à deux mains, tenue sur le côté sans bouger (anti-rotation) : 3 × 10 secondes par côté","Bird dog (bras et jambe opposés tendus à quatre pattes) : 3 × 10 par côté","Bercement ventre creux : 3 × 10"],
    exos18:["Planche sur les coudes : 4 × 45 secondes","Anti-rotation serviette tendue : 3 × 15 secondes par côté","Bird dog : 3 × 12 par côté","Bercement ventre creux : 3 × 15"],
    conseil:"Rester stable quand une force veut te déséquilibrer, c'est exactement ce qui se passe au moment où le portillon tombe. Plus tu es solide du tronc, plus ta poussée part droit dans le vélo." },
  jeudi:{ titre:"Premiers sauts", focus:"Découvrir l'explosivité des jambes en douceur",
    exos12:["Squats sautés (saute en haut, atterris souple) : 4 × 6 (récup 60 s)","Fentes sautées en changeant de jambe : 3 × 8 au total (récup 60 s)","Sauts sur place genoux vers la poitrine : 3 × 6 (récup 60 s)","Planche : 3 × 25 secondes"],
    exos18:["Squats sautés : 4 × 8 (récup 60 s)","Fentes sautées en changeant de jambe : 3 × 10 (récup 60 s)","Sauts genoux-poitrine : 3 × 8 (récup 60 s)","Planche : 3 × 35 secondes"],
    conseil:"La réception compte autant que le saut. Atterris genoux pliés, sans bruit. Un atterrissage maîtrisé protège tes genoux et prépare le rebond — la même qualité qui te sert sur les bosses de la première ligne." } },

{ s:4, phase:"Fondations", titre:"Construire la confiance par les preuves",
  mental:{ titre:"Le carnet de preuves",
    pourquoi:"Ta confiance ne doit pas dépendre de tes résultats — sinon elle s'effondre à chaque manche ratée. Elle doit reposer sur des PREUVES de ta progression, que tu contrôles totalement.",
    consigne:"Chaque soir cette semaine, note 3 progrès de ta journée. Pas des résultats — des progrès : un start plus net, une série tenue, un appui mieux placé, une émotion mieux gérée. Tu bâtis un dossier que personne ne peut t'enlever.",
    declencheur:"À la fin de la semaine, tu auras 21 preuves écrites que tu progresses. Relis-les avant ta prochaine course : c'est ça, la vraie confiance." },
  lundi:{ titre:"Force complète", focus:"Renforcer toute la chaîne de poussée",
    exos12:["Squats : 4 × 12","Pompes (sur les genoux si besoin) : 4 × 6","Fentes arrière : 3 × 8 par jambe","Planche + planche latérale : 3 tours (20 s chacune)"],
    exos18:["Squats : 4 × 18","Pompes : 4 × 12","Fentes arrière : 3 × 12 par jambe","Planche + planche latérale : 3 tours (35 s chacune)"],
    conseil:"On monte un peu le volume cette semaine. Si une série devient facile, ralentis la descente plutôt que d'ajouter des répétitions — la qualité avant la quantité." },
  jeudi:{ titre:"Apprendre à rebondir", focus:"Des jambes-ressort pour le start",
    exos12:["Sauts en hauteur sur place : 4 × 6 (récup 60 s)","Talons-fesses rapides sur place : 4 × 15 secondes","Pas chassés explosifs sur le côté : 3 × 8 par côté (récup 60 s)","Ventre creux tenu (hollow) : 3 × 20 secondes"],
    exos18:["Sauts en hauteur sur place : 4 × 8 (récup 60 s)","Talons-fesses rapides : 4 × 20 secondes","Pas chassés explosifs : 3 × 10 par côté (récup 60 s)","Ventre creux tenu : 3 × 30 secondes"],
    conseil:"Pense « ressort » : imagine que le sol est brûlant, tu y restes le moins longtemps possible. C'est exactement la sensation des premiers coups de pédale après le portillon." } },

{ s:5, phase:"Fondations", titre:"La routine d'avant-course",
  mental:{ titre:"Construire ta séquence rituelle",
    pourquoi:"Les meilleurs pilotes font TOUJOURS la même chose avant de s'engager dans la grille. Cette répétition crée un réflexe : ton cerveau associe la séquence à l'état « prêt à exploser ». Tu n'as plus à te demander comment te sentir — ton rituel s'en charge.",
    consigne:"Définis une séquence de 10 minutes, toujours identique, à faire avant chaque entraînement cette semaine : même échauffement, même ordre, mêmes 3 respirations, ton mot-ancre. Note-la sur papier. Répète-la à l'identique.",
    declencheur:"Au bout d'une semaine, le simple fait de commencer ta séquence te mettra en état de start. Tu auras un bouton « on »." },
  lundi:{ titre:"Gainage qui tient sous fatigue", focus:"Garder un tronc solide même fatigué",
    exos12:["Planche : 4 × 35 secondes","Planche latérale : 3 × 25 secondes par côté","Bercement ventre creux : 4 × 12","Superman dynamique (monte-descends) : 3 × 12"],
    exos18:["Planche : 4 × 50 secondes","Planche latérale : 3 × 35 secondes par côté","Bercement ventre creux : 4 × 18","Superman dynamique : 3 × 16"],
    conseil:"Quand ça brûle, respire au lieu de bloquer ta respiration. Apprendre à rester gainé en respirant, c'est apprendre à rester solide sur toute la première ligne, pas juste au start." },
  jeudi:{ titre:"Puissance des jambes", focus:"Monter en intensité sur la poussée",
    exos12:["Squats sautés : 4 × 8 (récup 60 s)","Fentes sautées : 4 × 6 par jambe (récup 60 s)","Montées explosives sur une marche : 3 × 8 par jambe (récup 60 s)","Mollets sautés (petits sauts sur la pointe des pieds) : 4 × 12 (récup 60 s)"],
    exos18:["Squats sautés : 4 × 10 (récup 60 s)","Fentes sautées : 4 × 8 par jambe (récup 60 s)","Montées explosives sur une marche : 3 × 10 par jambe (récup 60 s)","Mollets sautés : 4 × 18 (récup 60 s)"],
    conseil:"Repos complet entre les séries (90 secondes). On cherche la puissance, pas l'épuisement. Chaque saut doit être à 100 % — comme chaque start doit être ton meilleur." } },

{ s:6, phase:"Fondations", titre:"Bilan & ancrage du bloc 1",
  mental:{ titre:"La visualisation du start parfait",
    pourquoi:"Ton cerveau ne fait pas la différence entre un start réellement exécuté et un start intensément visualisé. En te voyant réussir ton départ, tu construis le circuit du geste — avant même de le faire sur la piste.",
    consigne:"3 fois cette semaine, 5 minutes, yeux fermés : visualise ton start parfait. Vois la grille, entends le bip, sens le portillon tomber. Vois ta poussée, tes premiers coups de pédale parfaits, ta sortie devant. Ressens-le, ne te contente pas de le regarder.",
    declencheur:"Ce que tu répètes dans ta tête, ton corps le reproduit. Tu prépares ton système nerveux à exploser dès que la porte tombe." },
  lundi:{ titre:"Circuit complet du bloc 1", focus:"Tester tes progrès depuis la semaine 1",
    exos12:["Circuit 3 tours : 10 squats + 6 pompes + 20 s planche + 8 fentes sautées","Repos 90 s entre les tours","Pour finir : ventre creux 3 × 20 secondes"],
    exos18:["Circuit 3 tours : 15 squats + 10 pompes + 30 s planche + 10 fentes sautées","Repos 90 s entre les tours","Pour finir : ventre creux 3 × 30 secondes"],
    conseil:"Compare ta sensation à la semaine 1. Tu vas sentir la différence : plus stable, plus de jus dans les jambes. C'est ça, les fondations qui paient." },
  jeudi:{ titre:"Test d'explosivité", focus:"Mesurer le rebond gagné",
    exos12:["Saut en longueur sans élan : 5 essais, note ta meilleure distance","Squats sautés : 4 × 8 (récup 60 s)","Pas chassés explosifs : 3 × 10 par côté (récup 60 s)","Planche finale : 3 × 30 secondes"],
    exos18:["Saut en longueur sans élan : 5 essais, note ta meilleure distance","Squats sautés : 4 × 10 (récup 60 s)","Pas chassés explosifs : 3 × 12 par côté (récup 60 s)","Planche finale : 3 × 40 secondes"],
    conseil:"Note ta distance de saut sur ton carnet. On la re-testera en semaine 12 et 24. Tu vas voir ta puissance de jambes grimper noir sur blanc." } },

// ─────────────────────────── BLOC 2 · CONSTRUCTION ───────────────────────────
{ s:7, phase:"Construction", titre:"Lancer la machine explosive",
  mental:{ titre:"Le déclencheur physique",
    pourquoi:"Tu peux créer un geste qui rappelle instantanément ton meilleur état. Les meilleurs pilotes serrent le guidon d'une certaine façon, prennent une inspiration nette — un geste précis qui dit au cerveau « on y va ».",
    consigne:"Choisis un geste simple et discret (serrer le poing, deux respirations sèches, caler tes mains sur le guidon). Répète-le 50 fois cette semaine, toujours juste avant une série explosive, en étant à fond. Tu lies le geste à l'état de start.",
    declencheur:"Bientôt, ce geste suffira à te mettre en mode attaque. Un raccourci direct vers ton meilleur start." },
  lundi:{ titre:"Détente explosive", focus:"Développer la puissance de poussée des jambes",
    exos12:["Squats sautés le plus haut possible : 5 × 5 (récup 60 s)","Sauts groupés genoux-poitrine : 4 × 6 (récup 60 s)","Fentes sautées explosives : 4 × 6 par jambe (récup 60 s)","Planche : 3 × 35 secondes"],
    exos18:["Squats sautés le plus haut possible : 5 × 6 (récup 60 s)","Sauts groupés genoux-poitrine : 4 × 8 (récup 60 s)","Fentes sautées explosives : 4 × 8 par jambe (récup 60 s)","Planche : 3 × 45 secondes"],
    conseil:"Qualité avant tout. Repos 90 à 120 secondes entre les séries. Chaque saut au maximum de ta hauteur. Si tu baisses en hauteur, repose-toi plus longtemps." },
  jeudi:{ titre:"Le start au sol et sur le vélo", focus:"Reproduire l'explosion du portillon",
    exos12:["Départ sprint sur 5 mètres depuis ta position de start : 6 fois (récup complète)","Squat sauté en partant de la position basse : 5 × 5 (récup 60 s)","Pompes explosives (les mains décollent un peu) : 4 × 4 (récup 60 s)","Si tu as le vélo : 6 starts sur grille ou ligne tracée, poussée maximale"],
    exos18:["Départ sprint sur 5 mètres depuis ta position de start : 6 fois (récup complète)","Squat sauté en partant de la position basse : 5 × 6 (récup 60 s)","Pompes explosives : 4 × 6 (récup 60 s)","Si tu as le vélo : 8 starts sur grille, poussée maximale, récup complète"],
    conseil:"Le sprint de 5 mètres reproduit l'explosion du portillon. Pars de ta vraie position de start : bras fléchis, poids avant. Explose sur les 3 premiers appuis comme si la porte venait de tomber." } },

{ s:8, phase:"Construction", titre:"Le reset après l'erreur",
  mental:{ titre:"Le protocole de récupération mentale",
    pourquoi:"En BMX, une erreur arrive en une fraction de seconde : un mauvais start, un pied qui glisse. Ce qui sépare les bons des champions, c'est la VITESSE de récupération. Rumine 3 secondes de trop et tu perds toute la manche.",
    consigne:"À chaque erreur cette semaine (à l'entraînement, dans la vie), applique : 1) un mot bref (« suivant »), 2) une expiration franche, 3) regard vers l'avant. 3 secondes maximum. Entraîne ce réflexe jusqu'à ce qu'il devienne automatique.",
    declencheur:"Tu vas transformer tes erreurs en non-événements. L'erreur arrive, tu la lâches, tu continues à attaquer. C'est une compétence rare et décisive en course." },
  lundi:{ titre:"Force maximale des jambes", focus:"Le maximum de force par poussée",
    exos12:["Squats sur une jambe assistés (en te tenant à un appui) : 4 × 5 par jambe (récup 60 s)","Pompes pieds surélevés sur une marche : 4 × 6","Fentes bulgares (pied arrière posé sur un banc) : 3 × 8 par jambe (récup 60 s)","Planche latérale : 3 × 30 s par côté"],
    exos18:["Squats sur une jambe assistés : 4 × 8 par jambe (récup 60 s)","Pompes pieds surélevés : 4 × 8","Fentes bulgares : 3 × 10 par jambe (récup 60 s)","Planche latérale : 3 × 40 s par côté"],
    conseil:"On reste au poids du corps mais on cherche la difficulté avec une seule jambe à la fois. Un squat sur une jambe vaut deux squats sur deux jambes — et c'est exactement ce qui te sert à pousser fort sur chaque pédale." },
  jeudi:{ titre:"Vitesse de jambes", focus:"Pédaler vite dès les premiers mètres",
    exos12:["Talons-fesses ultra-rapides sur place : 6 × 12 secondes (récup 45 s)","Montées de genoux explosives : 5 × 8 secondes","Squats sautés rapides : 4 × 8 (récup 60 s)","Ventre creux tenu : 3 × 25 secondes"],
    exos18:["Talons-fesses ultra-rapides : 6 × 15 secondes (récup 45 s)","Montées de genoux explosives : 5 × 10 secondes","Squats sautés rapides : 4 × 10 (récup 60 s)","Ventre creux tenu : 3 × 30 secondes"],
    conseil:"La vitesse de jambes se travaille. Pense « pieds rapides, sol qui brûle ». C'est la fréquence de pédalage qui fait la différence sur les premiers mètres après le portillon." } },

{ s:9, phase:"Construction", titre:"Oser l'engagement",
  mental:{ titre:"La décision d'engagement",
    pourquoi:"La peur te fait pousser pour ne pas rater au lieu de pousser pour gagner le start. Le remède : décider AVANT la course que tu t'engages à 100 % au portillon, quoi qu'il arrive. Une décision prise à froid tient mieux qu'un courage improvisé.",
    consigne:"Avant chaque session cette semaine, dis-toi à voix haute : « Quoi qu'il arrive, je m'engage à fond sur [mon start / ma première ligne]. » Puis fais-le. Une fois. Note ce que tu ressens après.",
    declencheur:"Chaque engagement tenu agrandit ta zone de confort. En quelques semaines, le portillon qui te faisait peur devient ton terrain de jeu." },
  lundi:{ titre:"Jambes-ressort réactives", focus:"Réduire le temps passé au sol",
    exos12:["Petits sauts pieds joints avant-arrière sur une ligne : 4 × 15 secondes","Petits sauts gauche-droite sur une ligne : 4 × 15 secondes","Squats sautés enchaînés : 4 × 6 (récup 60 s)","Planche dynamique : 3 × 30 secondes"],
    exos18:["Sauts pieds joints avant-arrière : 4 × 20 secondes","Sauts gauche-droite : 4 × 20 secondes","Squats sautés enchaînés : 4 × 8 (récup 60 s)","Planche dynamique : 3 × 40 secondes"],
    conseil:"Le contact au sol doit être le plus court possible. Imagine un sol brûlant. Cette réactivité fait la différence quand tu dois relancer entre deux bosses sur la première ligne." },
  jeudi:{ titre:"Start + relance", focus:"Enchaîner l'explosion et les premiers coups de pédale",
    exos12:["Sprint 8 mètres depuis ta position de start : 6 fois (récup complète)","Squat sauté + sprint 5 mètres enchaînés : 5 fois (récup 60 s)","Pompes explosives : 4 × 6 (récup 60 s)","Si vélo : 6 starts + maintien de vitesse sur 15 mètres"],
    exos18:["Sprint 10 mètres depuis ta position de start : 6 fois (récup complète)","Squat sauté + sprint 5 mètres enchaînés : 5 fois (récup 60 s)","Pompes explosives : 4 × 8 (récup 60 s)","Si vélo : 8 starts + maintien de vitesse sur 20 mètres"],
    conseil:"En BMX, le start ne suffit pas : il faut tenir la vitesse sur la première ligne. On enchaîne explosion puis relance pour habituer ton corps à ne jamais relâcher après le portillon." } },

{ s:10, phase:"Construction", titre:"Séparer ta valeur de tes résultats",
  mental:{ titre:"Les 3 critères qui ne dépendent pas du classement",
    pourquoi:"Si tu juges ta valeur sur ta place à l'arrivée, tu seras malheureux la plupart du temps. Évalue-toi plutôt sur ce que tu contrôles : ton engagement au portillon, ta poussée, ta gestion mentale.",
    consigne:"Définis 3 critères de « bon run » qui ne dépendent PAS du classement. Exemple : « je me suis engagé d'entrée », « j'ai gardé mon calme dans la grille », « j'ai relancé après mon erreur ». Évalue-toi sur ces 3 critères après chaque session cette semaine.",
    declencheur:"Tu vas reprendre le pouvoir sur ta satisfaction. Un bon run devient possible même sans podium — ce qui, paradoxalement, t'amène plus souvent devant." },
  lundi:{ titre:"Force d'une seule jambe", focus:"Équilibrer les deux jambes pour une poussée régulière",
    exos12:["Fentes bulgares : 4 × 8 par jambe (récup 60 s)","Montées sur banc explosives : 4 × 8 par jambe (récup 60 s)","Pompes mains rapprochées : 3 × 6","Planche latérale dynamique : 3 × 8 par côté"],
    exos18:["Fentes bulgares : 4 × 10 par jambe (récup 60 s)","Montées sur banc explosives : 4 × 10 par jambe (récup 60 s)","Pompes mains rapprochées : 3 × 10","Planche latérale dynamique : 3 × 12 par côté"],
    conseil:"Beaucoup de pilotes ont une jambe plus forte que l'autre. Le travail sur une seule jambe corrige ce déséquilibre — la clé d'une poussée régulière et puissante sur les deux pédales." },
  jeudi:{ titre:"Explosivité de tout le corps", focus:"Coordonner les bras et les jambes",
    exos12:["Burpees (descente-pompe-saut) sans la pompe pour commencer : 4 × 6 (récup 60 s)","Squats sautés : 4 × 8 (récup 60 s)","Pompes rapides : 3 × 5","Ventre creux tenu : 3 × 25 secondes"],
    exos18:["Burpees explosifs avec saut haut : 4 × 8 (récup 60 s)","Squats sautés : 4 × 10 (récup 60 s)","Pompes sautées (les mains décollent) : 3 × 5 (récup 60 s)","Ventre creux tenu : 3 × 35 secondes"],
    conseil:"Le start engage tout le corps : tu tires sur le guidon avec les bras pendant que les jambes poussent. Les burpees entraînent cette coordination entre le haut et le bas du corps." } },

{ s:11, phase:"Construction", titre:"Tenir le niveau sous fatigue",
  mental:{ titre:"Le focus sur l'action présente",
    pourquoi:"Quand la fatigue arrive en fin de manche, ton cerveau veut penser au résultat. C'est exactement ce qui te fait craquer. Le remède : ramener ton attention sur UNE action concrète.",
    consigne:"Cette semaine, sur tes séances les plus dures, quand la fatigue monte, fixe ton attention sur une seule chose technique (« pieds rapides », « regard loin », « tronc gainé »). Pas le chrono, pas la fin. Juste l'action présente.",
    declencheur:"Tu vas découvrir que la fatigue mentale vient surtout des pensées de résultat. En te concentrant sur le geste, tu tiens beaucoup plus longtemps — jusqu'à la dernière ligne droite." },
  lundi:{ titre:"Tenir la force dans la durée", focus:"Être aussi fort à la fin qu'au début",
    exos12:["Circuit 3 tours : 12 squats + 8 fentes par jambe + 25 s planche","Repos 60 s entre les tours","Pour finir : 3 × 12 squats sautés"],
    exos18:["Circuit 4 tours : 15 squats + 10 fentes par jambe + 30 s planche","Repos 60 s entre les tours","Pour finir : 3 × 20 squats sautés"],
    conseil:"On ajoute du volume pour préparer ta capacité à répéter l'effort. Sur une journée de course, tu enchaînes plusieurs manches : le but est d'être aussi fort à la dernière qu'à la première." },
  jeudi:{ titre:"Répéter les starts", focus:"Garder un start explosif même fatigué",
    exos12:["6 starts sprint 8 mètres depuis position de start, récup 60 s seulement","Squats sautés : 4 × 8 (récup 60 s)","Planche : 3 × 35 secondes","Si vélo : 6 starts en manche, peu de récup"],
    exos18:["8 starts sprint 10 mètres depuis position de start, récup 60 s seulement","Squats sautés : 4 × 10 (récup 60 s)","Planche : 3 × 45 secondes","Si vélo : 8 starts en manche, peu de récup"],
    conseil:"Récup courte volontairement : en compétition tu enchaînes les manches avec peu de repos. On entraîne ton start à rester explosif même quand tu commences à fatiguer." } },

{ s:12, phase:"Construction", titre:"Bilan & ancrage du bloc 2",
  mental:{ titre:"Visualisation du run complet",
    pourquoi:"Tu as travaillé le start, le reset, l'engagement. Maintenant on assemble : visualise un run entier, du portillon à la ligne, en intégrant tous tes outils mentaux.",
    consigne:"3 fois cette semaine, 7 minutes : visualise une manche complète. Le start (ton rituel), l'explosion du portillon, une erreur (ton reset en 3 s), un engagement osé dans un virage, la ligne franchie. Vis-la entièrement.",
    declencheur:"Tu programmes un run parfait dans ton système nerveux. Le jour de la course, ton corps suivra le chemin que tu auras tracé dans ta tête." },
  lundi:{ titre:"Test de puissance", focus:"Mesurer tes gains depuis la semaine 6",
    exos12:["Saut en longueur sans élan : 5 essais (compare à la semaine 6)","Nombre de squats sautés en 30 secondes : note le chiffre","Circuit complet 3 tours","Planche : note ton temps max"],
    exos18:["Saut en longueur sans élan : 5 essais (compare à la semaine 6)","Nombre de squats sautés en 30 secondes : note le chiffre","Circuit complet 3 tours","Planche : note ton temps max"],
    conseil:"Note tous tes chiffres sur ton carnet. Tu vas voir des progrès nets par rapport à la semaine 6. C'est la preuve concrète que tes jambes deviennent plus puissantes." },
  jeudi:{ titre:"Start chronométré", focus:"Évaluer ton explosion",
    exos12:["6 starts sprint 8 mètres depuis position de start (fais-toi chronométrer si possible)","Note ton meilleur temps","Squats sautés : 4 × 8 (récup 60 s)","Ventre creux tenu : 3 × 30 secondes"],
    exos18:["6 starts sprint 10 mètres depuis position de start (fais-toi chronométrer si possible)","Note ton meilleur temps","Squats sautés : 4 × 10 (récup 60 s)","Ventre creux tenu : 3 × 40 secondes"],
    conseil:"Garde une trace de ton meilleur start. On le bat en semaine 18 et 24. Le start, c'est l'arme numéro 1 du BMX Race : la moitié de la course se joue sur les 50 premiers mètres." } },

// ─────────────────────────── BLOC 3 · PUISSANCE ───────────────────────────
{ s:13, phase:"Puissance", titre:"Maîtriser la pression de l'enjeu",
  mental:{ titre:"S'habituer à la pression par petites doses",
    pourquoi:"On ne gère pas la pression en l'évitant, mais en s'y habituant petit à petit. Tu vas créer volontairement de l'enjeu à l'entraînement pour que la course paraisse plus facile.",
    consigne:"Cette semaine, mets-toi sous pression pour de faux : annonce à voix haute un objectif avant un exercice (« je fais 6 starts parfaits »), filme-toi, ou demande à quelqu'un de te regarder. Apprends à performer SOUS le regard.",
    declencheur:"Plus tu t'exposes à une pression que tu choisis, moins la pression de la course te fait peur. Tu inverses le rapport de force." },
  lundi:{ titre:"Force explosive lourde", focus:"Le maximum de puissance par poussée",
    exos12:["Squats sur une jambe assistés : 4 × 5 par jambe (récup 60 s)","Sauts sur une surface basse et stable (marche) : 4 × 5 (récup 60 s)","Pompes explosives : 4 × 4 (récup 60 s)","Anti-rotation serviette tendue : 3 × 12 par côté"],
    exos18:["Squats sur une jambe (pistol assisté) : 4 × 6 par jambe (récup 60 s)","Sauts sur un banc solide : 4 × 6 (récup 60 s)","Pompes explosives claquées si possible : 4 × 5 (récup 60 s)","Anti-rotation serviette tendue : 3 × 15 par côté"],
    conseil:"On cherche la puissance pure : peu de répétitions, intensité maximale, récup complète. Chaque effort doit être ton meilleur. C'est cette force max qui fait sauter le portillon." },
  jeudi:{ titre:"Puissance des premiers mètres", focus:"Accélérer fort dès la sortie du portillon",
    exos12:["Sprints 10 mètres départ arrêté : 6 fois (récup 2 min)","Squat sauté + sprint immédiat : 5 fois (récup 60 s)","Montées explosives sur banc : 4 × 6 par jambe (récup 60 s)","Bercement ventre creux : 4 × 15"],
    exos18:["Sprints 15 mètres départ arrêté : 6 fois (récup 2 min)","Squat sauté + sprint immédiat : 5 fois (récup 60 s)","Montées explosives sur banc : 4 × 8 par jambe (récup 60 s)","Bercement ventre creux : 4 × 20"],
    conseil:"L'accélération des premiers mètres décide souvent qui prend le holeshot (le premier virage). Ces sprints courts à fond construisent la puissance qui te met devant dès le portillon." } },

{ s:14, phase:"Puissance", titre:"La confiance inconditionnelle",
  mental:{ titre:"Les ancres de confiance",
    pourquoi:"Ta confiance doit tenir même après une mauvaise course. Pour ça, elle doit être ancrée sur des constantes que tu contrôles toujours : ton attitude, ton engagement, ton travail — jamais ta place à l'arrivée.",
    consigne:"Définis 2-3 constantes qui ne dépendent jamais du résultat : « je m'applique toujours », « je m'engage au portillon », « je reste correct même quand ça va mal ». Chaque jour cette semaine, vérifie que tu les as respectées. Ta confiance s'ancre là.",
    declencheur:"Tu construis une confiance qui ne s'effondre plus, parce qu'elle ne dépend plus de choses que tu ne maîtrises pas (le tirage, les autres pilotes, la piste)." },
  lundi:{ titre:"Puissance et stabilité", focus:"Être fort même en déséquilibre",
    exos12:["Fentes bulgares sautées : 4 × 6 par jambe (récup 60 s)","Planche les pieds sur une serviette roulée (instable) : 4 × 25 s","Pompes lentes : 4 × 8","Anti-rotation serviette tendue : 3 × 12 par côté"],
    exos18:["Fentes bulgares sautées : 4 × 8 par jambe (récup 60 s)","Planche pieds sur surface instable : 4 × 30 s","Pompes lestées (petit sac à dos) : 4 × 8","Anti-rotation serviette tendue : 3 × 15 par côté"],
    conseil:"En course, ta force doit s'exprimer en mouvement, sur un vélo qui bouge dans tous les sens. On entraîne la puissance en condition instable, plus proche de la réalité de la piste." },
  jeudi:{ titre:"Starts répétés", focus:"Un start aussi puissant au 8e qu'au 1er",
    exos12:["6 sprints 12 mètres, récup 90 s","Squats sautés : 4 × 10 (récup 60 s)","Talons-fesses rapides : 4 × 15 secondes","Planche : 3 × 40 secondes"],
    exos18:["8 sprints 15 mètres, récup 90 s","Squats sautés : 4 × 12 (récup 60 s)","Talons-fesses rapides : 4 × 20 secondes","Planche : 3 × 45 secondes"],
    conseil:"On augmente le nombre de starts. Objectif : que ton dernier sprint soit aussi puissant que le premier. C'est ça, la régularité qui fait gagner sur une journée de course." } },

{ s:15, phase:"Puissance", titre:"Attaquer la difficulté technique",
  mental:{ titre:"La visualisation des situations difficiles",
    pourquoi:"Les sections qui te font hésiter (un saut, un virage relevé) se débloquent d'abord dans la tête. En les visualisant réussies des dizaines de fois, tu enlèves la peur avant même d'y être.",
    consigne:"Identifie LA section qui te fait le plus hésiter sur la piste. Cette semaine, visualise-la réussie 10 fois par jour, en détail : ton approche, ton geste, ta réussite. Puis, à l'entraînement, engage-la avec ton mot-ancre.",
    declencheur:"La section qui te bloquait va devenir un endroit où tu prends du temps aux autres. La peur cède quand le cerveau a déjà « vu » la réussite." },
  lundi:{ titre:"Détente verticale", focus:"Sauter plus haut, être plus explosif",
    exos12:["Sauts en hauteur maximum : 5 × 4 (récup 60 s)","Sauts groupés genoux-poitrine : 4 × 6 (récup 60 s)","Squats sur une jambe assistés : 4 × 5 par jambe (récup 60 s)","Superman + ventre creux en alternance : 3 × 25 s"],
    exos18:["Sauts en hauteur maximum : 5 × 5 (récup 60 s)","Sauts groupés genoux-poitrine : 4 × 8 (récup 60 s)","Squats sur une jambe : 4 × 6 par jambe (récup 60 s)","Superman + ventre creux en alternance : 3 × 30 s"],
    conseil:"La détente verticale te sert à pomper dans les bosses et à passer les sauts. Plus de détente = plus d'options pour faire la différence sur la première ligne." },
  jeudi:{ titre:"Pédaler vite et fort", focus:"Produire de la vitesse efficacement",
    exos12:["Squats pulsés (petits rebonds en position basse) : 4 × 15 (récup 60 s)","Sauts avant-arrière rapides : 4 × 15 secondes","Fentes sautées : 4 × 8 (récup 60 s)","Planche dynamique : 3 × 35 secondes"],
    exos18:["Squats pulsés : 4 × 20 (récup 60 s)","Sauts avant-arrière rapides : 4 × 20 secondes","Fentes sautées : 4 × 10 (récup 60 s)","Planche dynamique : 3 × 40 secondes"],
    conseil:"Produire de la vitesse repose sur des jambes qui poussent vite ET fort. Ces squats pulsés entraînent exactement le ressort dont tu as besoin pour relancer après chaque virage." } },

{ s:16, phase:"Puissance", titre:"L'exigence juste",
  mental:{ titre:"Transformer l'exigence toxique",
    pourquoi:"Si tu te démolis à chaque erreur, ton exigence te détruit au lieu de te tirer vers le haut. L'exigence juste vise le progrès, pas la perfection. Elle est ferme sur l'effort, douce sur le résultat.",
    consigne:"Cette semaine, à chaque fois que tu te critiques durement, reformule comme le ferait un bon coach : remplace « je suis nul » par « qu'est-ce que j'ajuste au prochain start ? ». Note 3 fois où tu as réussi ce changement.",
    declencheur:"Tu vas découvrir que tu progresses PLUS vite en étant exigeant ET bienveillant avec toi-même. La dureté envers soi est un frein, pas un moteur." },
  lundi:{ titre:"Pic de force", focus:"Le maximum de force du bloc",
    exos12:["Squats sur une jambe assistés : 4 × 5 par jambe (récup 60 s)","Sauts sur un banc : 5 × 4 (récup 60 s)","Pompes explosives : 4 × 5 (récup 60 s)","Planche : 3 × 40 secondes"],
    exos18:["Squats sur une jambe (pistol) : 4 × 6 par jambe (récup 60 s)","Sauts sur banc haut : 5 × 5 (récup 60 s)","Pompes explosives : 4 × 6 (récup 60 s)","Planche : 3 × 45 secondes"],
    conseil:"Tu es à mi-chemin du bloc puissance. Si les squats sur une jambe commencent à venir, c'est un excellent marqueur de force — directement utile pour écraser chaque pédale au start." },
  jeudi:{ titre:"Start maximal", focus:"L'explosion pure au portillon",
    exos12:["6 sprints 10 mètres depuis position de start, à fond, récup 2 min","Squat sauté max : 5 × 4 (récup 60 s)","Burpees explosifs : 3 × 6 (récup 60 s)","Ventre creux tenu : 3 × 40 secondes"],
    exos18:["6 sprints 10 mètres depuis position de start, à fond, récup 2 min","Squat sauté max : 5 × 5 (récup 60 s)","Burpees explosifs : 3 × 8 (récup 60 s)","Ventre creux tenu : 3 × 45 secondes"],
    conseil:"Récup longue, intensité totale. On cherche le meilleur start possible, pas l'endurance. Chaque départ doit être ta meilleure explosion — comme en finale." } },

{ s:17, phase:"Puissance", titre:"Gérer l'adversaire plus fort",
  mental:{ titre:"Faire sa propre course",
    pourquoi:"Quand un pilote plus fort est dans ta grille, ton cerveau veut le surveiller — et tu perds le focus sur TON start. Le remède : ramener toute ton attention sur ton plan, comme s'il n'existait pas.",
    consigne:"Cette semaine, à chaque exercice, concentre-toi sur TON exécution sans te comparer à personne. Si tu t'entraînes avec d'autres, entraîne-toi à ne PAS les regarder dans la grille, à rester dans ta bulle. Note quand tu y arrives.",
    declencheur:"Tu vas réaliser que tes meilleurs starts arrivent quand tu oublies les autres. La comparaison vole ton énergie ; le focus la concentre sur le portillon." },
  lundi:{ titre:"Convertir la force en vitesse", focus:"Être fort VITE",
    exos12:["Squats sautés (petit sac à dos léger) : 4 × 6 (récup 60 s)","Fentes sautées explosives : 4 × 6 par jambe (récup 60 s)","Sauts en longueur enchaînés : 4 × 4 (récup 60 s)","Planche latérale : 3 × 30 s par côté"],
    exos18:["Squats sautés lestés léger : 4 × 8 (récup 60 s)","Fentes sautées explosives : 4 × 8 par jambe (récup 60 s)","Sauts en longueur enchaînés : 4 × 6 (récup 60 s)","Planche latérale : 3 × 40 s par côté"],
    conseil:"On lie la force que tu as construite à la vitesse d'exécution. Ce qui compte au start, ce n'est pas juste d'être fort, c'est d'être fort VITE — la force doit sortir d'un coup." },
  jeudi:{ titre:"Tenir la puissance sur la durée", focus:"Garder la vitesse jusqu'au bout de la ligne",
    exos12:["8 sprints 12 mètres, récup 75 s","Squats sautés : 4 × 10 (récup 60 s)","Grimpeur au sol : 4 × 25 secondes","Planche : 3 × 45 secondes"],
    exos18:["10 sprints 12 mètres, récup 75 s","Squats sautés : 4 × 12 (récup 60 s)","Grimpeur au sol : 4 × 30 secondes","Planche : 3 × 50 secondes"],
    conseil:"On monte le nombre de sprints. La fatigue va venir — c'est le but. Apprends à garder une bonne technique de pédalage même quand les jambes brûlent en fin de ligne." } },

{ s:18, phase:"Puissance", titre:"Bilan & ancrage du bloc 3",
  mental:{ titre:"Visualisation sous pression maximale",
    pourquoi:"On combine tout : tu vas visualiser ta course la plus importante, avec le maximum d'enjeu, en restant maître de tes émotions grâce à tous tes outils.",
    consigne:"3 fois cette semaine, 8 minutes : visualise TA course objectif de la saison. Le contexte (le public, l'enjeu), tes émotions dans la grille, ton rituel, ton start explosif, ta gestion de la pression, ta première ligne propre. Termine toujours par la réussite.",
    declencheur:"Tu rends familière la situation la plus stressante. Le jour réel, ton cerveau pensera « je connais déjà ça » — et tu seras calme dans la grille là où les autres craquent." },
  lundi:{ titre:"Test de puissance", focus:"Mesurer les gains du bloc 3",
    exos12:["Saut en longueur sans élan : 5 essais (compare semaines 6 et 12)","Saut en hauteur max : note la hauteur","Nombre de squats sur une jambe par jambe : note le chiffre","Planche max : note le temps"],
    exos18:["Saut en longueur sans élan : 5 essais (compare semaines 6 et 12)","Saut en hauteur max : note la hauteur","Nombre de squats sur une jambe par jambe : note le chiffre","Planche max : note le temps"],
    conseil:"Tu devrais battre tes scores des bilans précédents. Ces chiffres sont la preuve que ton corps de pilote se transforme — plus de force, plus de détente." },
  jeudi:{ titre:"Start chronométré", focus:"Battre ton record du start",
    exos12:["6 sprints 10 mètres chronométrés depuis position de start","Compare à ton temps de la semaine 12","Squats sautés : 4 × 8 (récup 60 s)","Ventre creux tenu : 3 × 40 secondes"],
    exos18:["6 sprints 10 mètres chronométrés depuis position de start","Compare à ton temps de la semaine 12","Squats sautés : 4 × 10 (récup 60 s)","Ventre creux tenu : 3 × 45 secondes"],
    conseil:"Bats ton start de la semaine 12. Tu vas le voir noir sur blanc : ce qui te coûtait au portillon devient maintenant ton point fort." } },

// ─────────────────────────── BLOC 4 · PERFORMANCE ───────────────────────────
{ s:19, phase:"Performance", titre:"Transférer en course",
  mental:{ titre:"Les objectifs concrets de course",
    pourquoi:"Le jour de la course, tu ne dois penser ni au classement, ni à la technique abstraite — mais à 1 ou 2 objectifs concrets. Ça te donne un but qui ne dépend pas du résultat et libère ton naturel.",
    consigne:"Pour ta prochaine session-course cette semaine, choisis 1 ou 2 objectifs simples (ex : « je m'engage d'entrée au portillon », « je tiens mon pédalage jusqu'au premier virage »). Concentre-toi UNIQUEMENT dessus. Évalue-les après.",
    declencheur:"Tu vas sentir une libération : avec un objectif concret, ton corps fait ce qu'il sait faire au lieu d'être paralysé par l'enjeu." },
  lundi:{ titre:"Puissance spécifique BMX", focus:"Reproduire les efforts d'une manche",
    exos12:["Sprint 12 mètres + virage marqué (contourne un plot) : 6 fois","Squats sautés : 4 × 8 (récup 60 s)","Fentes sautées : 4 × 6 par jambe (récup 60 s)","Anti-rotation serviette : 3 × 12 par côté"],
    exos18:["Sprint 15 mètres + virage marqué : 6 fois","Squats sautés : 4 × 10 (récup 60 s)","Fentes sautées : 4 × 8 par jambe (récup 60 s)","Anti-rotation serviette : 3 × 15 par côté"],
    conseil:"On rapproche le travail de la réalité : explosion du start + relance dans le premier virage, comme sur une vraie piste de BMX." },
  jeudi:{ titre:"Enchaînement de manche", focus:"Simuler une manche complète",
    exos12:["Circuit : sprint 8 m + 5 squats sautés + sprint 8 m, 5 tours, récup 90 s","Pompes explosives : 4 × 5 (récup 60 s)","Bercement ventre creux : 4 × 15","Si vélo : 5 manches complètes"],
    exos18:["Circuit : sprint 10 m + 5 squats sautés + sprint 10 m, 6 tours, récup 90 s","Pompes explosives : 4 × 6 (récup 60 s)","Bercement ventre creux : 4 × 20","Si vélo : 6 manches complètes"],
    conseil:"Ce circuit imite la structure d'une manche de BMX : explosion au portillon, relances entre les bosses, maintien jusqu'à la ligne. Ton corps apprend l'enchaînement réel." } },

{ s:20, phase:"Performance", titre:"Le pic de concentration",
  mental:{ titre:"Le recentrage entre les manches",
    pourquoi:"En course, tu enchaînes plusieurs manches dans la journée. Entre chaque, tu dois pouvoir te recentrer en 20 secondes pour repartir neuf, sans traîner l'émotion de la précédente.",
    consigne:"Crée ton protocole de recentrage en 20 secondes : 3 respirations lentes, ton mot-ancre, regard fixé sur un point. Répète-le cette semaine entre chaque série d'exercices, jusqu'à ce qu'il soit fluide et automatique.",
    declencheur:"Le jour de la course, entre tes manches, tu auras un outil pour repartir à 100 % à chaque fois — là où les autres restent bloqués sur la manche d'avant." },
  lundi:{ titre:"Affûtage puissance", focus:"Garder la puissance, réduire le volume",
    exos12:["Squats sautés max : 4 × 5 (récup 60 s)","Sauts sur banc : 4 × 4 (récup 60 s)","Sprints 8 mètres : 5 fois (récup complète)","Planche : 3 × 35 secondes"],
    exos18:["Squats sautés max : 4 × 6 (récup 60 s)","Sauts sur banc : 4 × 5 (récup 60 s)","Sprints 10 mètres : 5 fois (récup complète)","Planche : 3 × 40 secondes"],
    conseil:"On entre en phase d'affûtage : moins de volume, mais on garde l'intensité. Le but est d'arriver frais et explosif le jour de la course, pas épuisé." },
  jeudi:{ titre:"Vitesse pure", focus:"Des jambes vives et rapides",
    exos12:["Talons-fesses ultra-rapides : 6 × 8 secondes","Squats sautés rapides : 4 × 6 (récup 60 s)","Starts explosifs 5 mètres : 6 fois (récup 90 s)","Ventre creux tenu : 3 × 35 secondes"],
    exos18:["Talons-fesses ultra-rapides : 6 × 10 secondes","Squats sautés rapides : 4 × 8 (récup 60 s)","Starts explosifs 5 mètres : 6 fois (récup 90 s)","Ventre creux tenu : 3 × 40 secondes"],
    conseil:"Efforts courts et explosifs uniquement. On garde le système nerveux vif et rapide, sans accumuler de fatigue. Tu veux des jambes qui répondent au quart de tour." } },

{ s:21, phase:"Performance", titre:"La routine du jour J",
  mental:{ titre:"Finaliser ta routine de course",
    pourquoi:"Le jour de la course ne s'improvise pas. Tu dois avoir une routine complète, de ton réveil jusqu'au portillon, qui te met dans le meilleur état possible sans que tu aies à réfléchir.",
    consigne:"Écris ta routine complète du jour de course : heure de réveil, petit-déjeuner, reconnaissance de la piste, échauffement, séquence d'avant-start, gestion entre les manches. Teste-la lors de ta prochaine session pour l'ajuster.",
    declencheur:"Une routine rodée enlève l'incertitude. Le jour J, tu n'as plus qu'à la dérouler — ton énergie va à la performance, pas à la gestion du stress." },
  lundi:{ titre:"Puissance fraîche", focus:"Qualité maximale, fatigue minimale",
    exos12:["Sprints 10 mètres : 5 fois (récup 2 min)","Squats sautés : 3 × 5 (récup 60 s)","Pompes explosives : 3 × 5 (récup 60 s)","Planche : 2 × 35 secondes"],
    exos18:["Sprints 12 mètres : 5 fois (récup 2 min)","Squats sautés : 3 × 6 (récup 60 s)","Pompes explosives : 3 × 6 (récup 60 s)","Planche : 2 × 40 secondes"],
    conseil:"Volume réduit, intensité haute. Tu dois finir la séance avec l'impression d'en avoir encore sous le pied. C'est voulu : on prépare la fraîcheur." },
  jeudi:{ titre:"Réveil du corps", focus:"Activer sans fatiguer",
    exos12:["Talons-fesses rapides : 4 × 8 secondes","Squats sautés : 3 × 5 (récup 60 s)","Starts 5 mètres : 4 fois (récup complète)","Mobilité + planche légère : 2 × 25 secondes"],
    exos18:["Talons-fesses rapides : 4 × 10 secondes","Squats sautés : 3 × 6 (récup 60 s)","Starts 5 mètres : 4 fois (récup complète)","Mobilité + planche légère : 2 × 30 secondes"],
    conseil:"Séance courte d'activation. On garde le système explosif allumé tout en restant frais pour la course. C'est ce que tu feras le matin d'une vraie compétition." } },

{ s:22, phase:"Performance", titre:"Le plaisir de rouler",
  mental:{ titre:"Retrouver le plaisir du vélo",
    pourquoi:"Tes meilleurs starts arrivent quand tu es dans le plaisir : concentré mais détendu, performant sans forcer. Cet état vient du plaisir, pas de la contrainte. On le cultive volontairement.",
    consigne:"Cette semaine, fais au moins une session avec une seule règle : aucun objectif de performance, juste le plaisir de rouler et de pousser. Reconnecte avec POURQUOI tu fais du BMX. Note ce que tu ressens.",
    declencheur:"Tu vas te rappeler que tu roules mieux quand tu prends du plaisir. Le plaisir n'est pas un luxe — c'est ton état de performance maximale." },
  lundi:{ titre:"Puissance en s'amusant", focus:"Performer en jouant",
    exos12:["Parcours libre de sauts et de sprints (invente-le) : 12 min","Squats sautés : 3 × 6 (récup 60 s)","Planche : 2 × 35 secondes"],
    exos18:["Parcours libre de sauts et de sprints (invente-le) : 15 min","Squats sautés : 3 × 8 (récup 60 s)","Planche : 2 × 40 secondes"],
    conseil:"Transforme la séance en jeu. Le corps apprend mieux dans le plaisir — et c'est exactement l'état que tu veux retrouver dans la grille de départ." },
  jeudi:{ titre:"Vitesse plaisir", focus:"De l'explosivité sans pression",
    exos12:["Starts en te chronométrant pour le fun : 6 essais","Talons-fesses rapides : 4 × 8 secondes","Sauts variés : 3 × 6 (récup 60 s)","Ventre creux tenu : 2 × 35 secondes"],
    exos18:["Starts en te chronométrant pour le fun : 6 essais","Talons-fesses rapides : 4 × 10 secondes","Sauts variés : 3 × 8 (récup 60 s)","Ventre creux tenu : 2 × 40 secondes"],
    conseil:"Joue avec ta vitesse, cherche à battre ton propre record en souriant. Le plaisir et la performance vont ensemble au start, jamais l'un contre l'autre." } },

{ s:23, phase:"Performance", titre:"Préparer le pic de forme",
  mental:{ titre:"La visualisation finale complète",
    pourquoi:"Tu as tous les outils. Cette semaine, on les assemble en une visualisation parfaite, répétée, qui programme ton meilleur run possible dans les moindres détails.",
    consigne:"Chaque jour cette semaine, 8 minutes : visualise ton run parfait du portillon à la ligne, en intégrant TOUT : routine, rituel, start explosif, gestion de la pression, première ligne propre, recentrage entre les manches, plaisir, ligne franchie. Vis-le, ne le regarde pas.",
    declencheur:"Tu auras répété ton run idéal des dizaines de fois dans ta tête. Le jour J, ce sera comme le refaire — ton corps connaîtra déjà le chemin." },
  lundi:{ titre:"Affûtage final", focus:"Fraîcheur et explosivité",
    exos12:["Sprints 8 mètres : 4 fois (récup complète)","Squats sautés : 3 × 4 (récup 60 s)","Pompes explosives : 2 × 5 (récup 60 s)","Planche : 2 × 25 secondes"],
    exos18:["Sprints 10 mètres : 4 fois (récup complète)","Squats sautés : 3 × 5 (récup 60 s)","Pompes explosives : 2 × 5 (récup 60 s)","Planche : 2 × 30 secondes"],
    conseil:"Très peu de volume. Tu prépares ton corps à exprimer son maximum. Reposé + explosif = pic de forme pour la course." },
  jeudi:{ titre:"Dernière activation", focus:"Allumer la mèche",
    exos12:["Talons-fesses rapides : 3 × 8 secondes","Starts 5 mètres : 4 fois (récup complète)","Squats sautés : 2 × 4 (récup 60 s)","Mobilité légère"],
    exos18:["Talons-fesses rapides : 3 × 10 secondes","Starts 5 mètres : 4 fois (récup complète)","Squats sautés : 2 × 5 (récup 60 s)","Mobilité légère"],
    conseil:"Séance ultra-courte. Le travail est fait. On garde juste le système nerveux vif et prêt à exploser au portillon." } },

{ s:24, phase:"Performance", titre:"Performer — et faire le bilan",
  mental:{ titre:"Le débrief de progression",
    pourquoi:"24 semaines de travail méritent d'être mesurées. Regarder le chemin parcouru ancre ta confiance dans des preuves solides — et trace ta suite.",
    consigne:"Relis ton carnet de preuves (semaine 4) et tes bilans physiques (semaines 6, 12, 18). Écris : 3 points forts que tu as consolidés, 2 points faibles que tu as corrigés, et ton prochain objectif. Partage-le avec Fabien via la messagerie.",
    declencheur:"Tu vas mesurer noir sur blanc ta transformation. Cette preuve de progression est la fondation de toute ta confiance future." },
  lundi:{ titre:"Test final complet", focus:"Mesurer 24 semaines de transformation",
    exos12:["Saut en longueur sans élan : compare aux semaines 6, 12, 18","Saut en hauteur max","Nombre max de squats sur une jambe par jambe","Planche max"],
    exos18:["Saut en longueur sans élan : compare aux semaines 6, 12, 18","Saut en hauteur max","Nombre max de squats sur une jambe par jambe","Planche max"],
    conseil:"Compare TOUS tes chiffres au départ. La progression que tu vois ici, c'est celle que tu mettras au portillon. Tu n'es plus le même pilote." },
  jeudi:{ titre:"Start record", focus:"Ta meilleure explosion",
    exos12:["6 sprints 10 mètres chronométrés depuis position de start","Bats ton record des semaines 12 et 18","Célèbre le travail accompli","Planche : 3 × 40 secondes"],
    exos18:["6 sprints 10 mètres chronométrés depuis position de start","Bats ton record des semaines 12 et 18","Célèbre le travail accompli","Planche : 3 × 45 secondes"],
    conseil:"Ton dernier start du programme. Donne tout. Puis regarde le chemin : de la semaine 1 à aujourd'hui, tu as construit un vrai pilote de BMX. La suite t'appartient." } },
];
