// ════════════════════════════════════════════════════════════════
//  AXE — PROGRAMME 24 SEMAINES · PRÉPARATION GÉNÉRALE · POIDS DU CORPS
//  Structure de chaque semaine :
//   { titre, phase, mental:{titre, pourquoi, consigne, declencheur},
//     lundi:{titre, focus, exos:[...], conseil},
//     jeudi:{...} }
//  Progression en 4 blocs de 6 semaines :
//   BLOC 1 (1-6)  : Fondations — gainage, posture, respiration
//   BLOC 2 (7-12) : Construction — explosivité, pliométrie, ancrage mental
//   BLOC 3 (13-18): Puissance — force, vitesse, gestion de la pression
//   BLOC 4 (19-24): Performance — transfert en compétition, pic de forme
// ════════════════════════════════════════════════════════════════

const SEMAINES = [
// ─────────────────────────── BLOC 1 · FONDATIONS ───────────────────────────
{ s:1, phase:"Fondations", titre:"Poser le socle",
  mental:{ titre:"Le scan de tension en 60 secondes",
    pourquoi:"Avant de gérer ton stress en compétition, il faut SENTIR où il se loge dans ton corps. La plupart des athlètes ne savent même pas qu'ils serrent les épaules ou la mâchoire avant de s'élancer — et ça leur coûte leur départ.",
    consigne:"Une fois par jour, assieds-toi 60 secondes. Pars des pieds et remonte lentement : pieds, mollets, cuisses, ventre, mains, épaules, mâchoire. À chaque zone, demande-toi : « est-ce tendu ? » Si oui, contracte fort 5 secondes, puis relâche d'un coup. Note mentalement les 2 zones les plus tendues.",
    declencheur:"En 7 jours, tu vas identifier TES zones de tension perso. C'est la première fois que tu prends le contrôle de quelque chose que tu subissais." },
  lundi:{ titre:"Gainage & posture", focus:"Construire le tronc qui transfère ta puissance",
    exos:["Gainage planche : 4 × 30 s, 45 s de repos","Gainage latéral : 3 × 20 s par côté","Superman au sol (bras+jambes décollés) : 3 × 12","Hollow hold (creux abdominal) : 3 × 20 s"],
    conseil:"Le gainage n'est pas un exercice d'abdos. C'est ce qui empêche ta puissance de se perdre quand tu produis un effort intense. Tiens-toi gainé comme une planche, pas le ventre creusé." },
  jeudi:{ titre:"Posture de départ", focus:"Apprendre la position d'attaque au sol",
    exos:["Squat isométrique position basse : 5 × 20 s (genoux fléchis, buste penché, bras prêts)","Fentes statiques : 3 × 10 par jambe","Pompes lentes (3 s descente) : 4 × 8","Chaise contre le mur : 3 × 30 s"],
    conseil:"Reproduis ta position d'attaque : poids vers l'avant, regard loin. Ton corps mémorise cette posture pour qu'elle devienne automatique le jour J." } },

{ s:2, phase:"Fondations", titre:"Respirer pour performer",
  mental:{ titre:"La cohérence cardiaque 5-5",
    pourquoi:"Ton rythme cardiaque pilote ton stress. En respirant à un rythme précis, tu envoies à ton cerveau le signal « tout va bien » — même quand l'enjeu est énorme. C'est physiologique, pas psychologique : ça marche à tous les coups.",
    consigne:"3 fois par jour : inspire 5 secondes par le nez, expire 5 secondes par la bouche. Pendant 5 minutes. Matin, midi, et surtout le soir avant de dormir. Compte dans ta tête.",
    declencheur:"Tu vas dormir mieux la veille des compétitions dès la 2e semaine. Ton corps apprend à se calmer sur commande." },
  lundi:{ titre:"Gainage dynamique", focus:"Le tronc en mouvement, comme en action",
    exos:["Planche avec touches d'épaule : 4 × 20 touches","Mountain climbers lents : 4 × 30 s","Dead bug (bras+jambe opposés) : 3 × 12","Gainage latéral avec rotation : 3 × 10 par côté"],
    conseil:"En mouvement, ton tronc travaille en permanence pour te stabiliser. On entraîne maintenant un gainage qui résiste ET qui bouge." },
  jeudi:{ titre:"Force des jambes", focus:"Construire la base de poussée",
    exos:["Squats au poids du corps : 4 × 15","Fentes marchées : 3 × 12 par jambe","Montées sur une marche/banc : 3 × 12 par jambe","Mollets debout : 4 × 20"],
    conseil:"Tempo lent à la descente (3 s), explosif à la montée. C'est ce contraste qui construit la puissance utile à tes efforts." } },

{ s:3, phase:"Fondations", titre:"Ancrer la concentration",
  mental:{ titre:"Le mot-ancre",
    pourquoi:"Quand ta tête part dans tous les sens avant l'effort, tu as besoin d'un point de retour immédiat. Un seul mot, répété, qui ramène toute ton attention sur l'instant.",
    consigne:"Choisis UN mot qui te met en état d'attaque : « explose », « maintenant », « léger », « devant »… À chaque séance physique cette semaine, répète-le mentalement au début de chaque série. Tu crées un lien entre ce mot et l'action.",
    declencheur:"À force de répétition, ce mot deviendra ton interrupteur de concentration. En compétition, tu le diras et ton focus reviendra net." },
  lundi:{ titre:"Gainage anti-rotation", focus:"Stabilité et contrôle du corps",
    exos:["Planche : 4 × 40 s","Pallof press (élastique ou serviette tendue) : 3 × 12 par côté","Bird dog : 3 × 12 par côté","Hollow rock (bercement creux) : 3 × 15"],
    conseil:"L'anti-rotation, c'est ce qui te garde stable quand une force veut te déséquilibrer. Plus tu es solide, plus tu gardes le contrôle." },
  jeudi:{ titre:"Explosivité débutante", focus:"Premiers sauts contrôlés",
    exos:["Squats sautés : 4 × 8 (réception souple)","Fentes sautées alternées : 3 × 10","Sauts sur place genoux poitrine : 3 × 8","Gainage planche : 3 × 30 s"],
    conseil:"La réception compte autant que le saut. Atterris genoux fléchis, en silence. Un atterrissage maîtrisé protège tes articulations et prépare le rebond." } },

{ s:4, phase:"Fondations", titre:"Construire la confiance par les preuves",
  mental:{ titre:"Le carnet de preuves",
    pourquoi:"Ta confiance ne doit pas dépendre de tes résultats — sinon elle s'effondre à chaque mauvaise compétition. Elle doit reposer sur des PREUVES de ta progression, que tu contrôles totalement.",
    consigne:"Chaque soir cette semaine, note 3 progrès de ta journée. Pas des résultats — des progrès : un geste mieux exécuté, une série tenue, un départ plus net à l'entraînement, une émotion mieux gérée. Tu bâtis un dossier que personne ne peut t'enlever.",
    declencheur:"À la fin de la semaine, tu auras 21 preuves écrites que tu progresses. Relis-les avant ta prochaine compétition : c'est ça, la vraie confiance." },
  lundi:{ titre:"Force complète", focus:"Renforcer l'ensemble de la chaîne",
    exos:["Squats : 4 × 15","Pompes : 4 × 10","Fentes arrière : 3 × 12 par jambe","Gainage planche + latéral : 3 tours (30 s chaque)"],
    conseil:"On augmente le volume cette semaine. Si une série devient facile, ralentis le tempo plutôt que d'ajouter des répétitions." },
  jeudi:{ titre:"Pliométrie légère", focus:"Apprendre à rebondir",
    exos:["Sauts verticaux : 4 × 8","Skipping haut (genoux hauts rapides) : 4 × 20 s","Pas chassés latéraux explosifs : 3 × 10 par côté","Hollow hold : 3 × 25 s"],
    conseil:"Pense « ressort » : le sol est chaud, tu y restes le moins longtemps possible. C'est exactement la sensation d'une bonne explosion." } },

{ s:5, phase:"Fondations", titre:"La routine pré-compétition",
  mental:{ titre:"Construire ta séquence rituelle",
    pourquoi:"Les meilleurs athlètes font TOUJOURS la même chose avant de performer. Cette répétition crée un réflexe : ton cerveau associe la séquence à l'état « prêt à performer ». Tu n'as plus à te demander comment te sentir — ton rituel s'en charge.",
    consigne:"Définis une séquence de 10 minutes, toujours identique, à faire avant chaque entraînement cette semaine : même ordre d'échauffement, même musique, mêmes 3 respirations, ton mot-ancre. Note-la sur papier. Répète-la à l'identique.",
    declencheur:"Au bout d'une semaine, le simple fait de commencer ta séquence te mettra en état de performance. Tu auras un bouton « on »." },
  lundi:{ titre:"Gainage avancé", focus:"Tenir plus longtemps sous fatigue",
    exos:["Planche : 4 × 50 s","Gainage latéral : 3 × 35 s par côté","Hollow rock : 4 × 20","Superman dynamique : 3 × 15"],
    conseil:"Quand ça brûle, respire au lieu de bloquer. Apprendre à rester gainé en respirant, c'est apprendre à rester solide en compétition." },
  jeudi:{ titre:"Puissance des jambes", focus:"Monter en intensité",
    exos:["Squats sautés : 4 × 10","Fentes sautées : 4 × 8 par jambe","Montées explosives sur marche : 3 × 10 par jambe","Mollets sautés : 4 × 15"],
    conseil:"Repos complet entre les séries (90 s). On cherche la puissance, pas l'épuisement. Chaque saut doit être à 100 %." } },

{ s:6, phase:"Fondations", titre:"Bilan & ancrage du bloc 1",
  mental:{ titre:"La visualisation de la performance parfaite",
    pourquoi:"Ton cerveau ne fait pas la différence entre un geste réellement exécuté et un geste intensément visualisé. En te voyant réussir ta performance, tu construis le circuit neuronal du geste — avant même de le réaliser.",
    consigne:"3 fois cette semaine, 5 minutes, yeux fermés : visualise ta performance parfaite. Vois le lieu, entends les sons, sens ton corps prêt. Vois le départ, ton explosion, tes premiers gestes parfaits. Ressens-le, ne te contente pas de le regarder.",
    declencheur:"Ce que tu répètes mentalement, ton corps le reproduit. Tu prépares ton système nerveux à exploser le jour J." },
  lundi:{ titre:"Circuit complet", focus:"Tester tes progrès du bloc 1",
    exos:["Circuit 3 tours : 12 squats + 8 pompes + 20 s planche + 10 fentes sautées","Repos 90 s entre les tours","Finition : hollow hold 3 × 30 s"],
    conseil:"Compare ta sensation à la semaine 1. Tu vas sentir la différence : plus stable, plus de jus. C'est ça, les fondations qui paient." },
  jeudi:{ titre:"Explosivité bilan", focus:"Mesurer le rebond gagné",
    exos:["Saut en longueur sans élan : 5 essais, note ta meilleure distance","Squats sautés : 4 × 10","Pas chassés explosifs : 3 × 12 par côté","Gainage final : 3 × 40 s"],
    conseil:"Note ta distance de saut. On la re-testera en semaine 12 et 24. Tu vas voir ta puissance grimper noir sur blanc." } },

// ─────────────────────────── BLOC 2 · CONSTRUCTION ───────────────────────────
{ s:7, phase:"Construction", titre:"Lancer la machine explosive",
  mental:{ titre:"Le déclencheur physique",
    pourquoi:"Tu peux créer un geste qui rappelle instantanément ton meilleur état. Les meilleurs athlètes serrent le poing, prennent une inspiration nette — un geste précis qui dit au cerveau « on y va ».",
    consigne:"Identifie un geste simple et discret (serrer le poing, taper 2 fois, une inspiration sèche). Répète-le 50 fois cette semaine, toujours juste avant une série explosive, en étant à fond. Tu lies le geste à l'état d'attaque.",
    declencheur:"Bientôt, ce geste suffira à te mettre en mode performance. Un raccourci direct vers ton meilleur niveau." },
  lundi:{ titre:"Pliométrie haute", focus:"Développer la puissance de détente",
    exos:["Squats sautés max hauteur : 5 × 6","Sauts groupés genoux-poitrine : 4 × 8","Fentes sautées explosives : 4 × 8 par jambe","Gainage planche : 3 × 45 s"],
    conseil:"Qualité > quantité. Repos 90-120 s. Chaque saut à 100 % de ta hauteur. Si tu baisses, repose-toi plus." },
  jeudi:{ titre:"Le départ au sol", focus:"Reproduire l'explosion initiale",
    exos:["Départ sprint 5 m depuis position d'attaque : 6 × (récup complète)","Squat saut depuis position basse : 5 × 6","Pompes explosives (mains décollent) : 4 × 6","Hollow rock : 3 × 20"],
    conseil:"Le départ sprint reproduit l'explosion initiale. Pars de ta position d'attaque. Explose sur les 3 premiers appuis comme au signal de départ." } },

{ s:8, phase:"Construction", titre:"Le reset après l'erreur",
  mental:{ titre:"Le protocole de récupération mentale",
    pourquoi:"En compétition, une erreur arrive en une fraction de seconde. Ce qui sépare les bons des champions, c'est la VITESSE de récupération. Rumine 3 secondes de trop, et tu perds l'épreuve entière.",
    consigne:"À chaque erreur cette semaine (à l'entraînement, dans la vie), applique : 1) un mot bref (« suivant »), 2) une expiration franche, 3) regard vers l'avant. 3 secondes maximum. Entraîne ce protocole jusqu'à ce qu'il devienne automatique.",
    declencheur:"Tu vas transformer tes erreurs en non-événements. L'erreur arrive, tu la lâches, tu continues. C'est une compétence rare et décisive." },
  lundi:{ titre:"Puissance maximale", focus:"Le maximum de force par mouvement",
    exos:["Squats lestés (sac à dos chargé) ou squats unijambe assistés : 4 × 8","Pompes pieds surélevés : 4 × 8","Fentes bulgares (pied arrière sur banc) : 3 × 10 par jambe","Gainage latéral : 3 × 40 s par côté"],
    conseil:"On reste au poids du corps mais on cherche la difficulté par les angles et l'unilatéral. Un squat sur une jambe vaut deux sur deux jambes." },
  jeudi:{ titre:"Vitesse de jambes", focus:"Cadence et fréquence d'exécution",
    exos:["Skipping ultra-rapide : 6 × 15 s (récup 45 s)","Montées de genoux explosives : 5 × 10 s","Squats sautés rapides : 4 × 10","Hollow hold : 3 × 30 s"],
    conseil:"La vitesse d'exécution se travaille. Pense « pieds rapides, sol qui brûle ». Fréquence maximale sur les efforts courts." } },

{ s:9, phase:"Construction", titre:"Oser l'engagement",
  mental:{ titre:"La décision proactive d'engagement",
    pourquoi:"La peur te fait jouer pour ne pas perdre au lieu de jouer pour gagner. Le remède : décider AVANT la compétition que tu t'engages à 100 %, quoi qu'il arrive. Une décision prise à froid tient mieux qu'un courage improvisé.",
    consigne:"Avant chaque session cette semaine, dis-toi à voix haute : « Quoi qu'il arrive, je m'engage à fond sur [un élément précis]. » Puis fais-le. Une fois. Note ce que tu ressens après.",
    declencheur:"Chaque engagement tenu agrandit ta zone de confort. En quelques semaines, ce qui te faisait peur devient ton terrain de jeu." },
  lundi:{ titre:"Pliométrie réactive", focus:"Réduire le temps de contact au sol",
    exos:["Sauts à pieds joints rapides (avant-arrière sur une ligne) : 4 × 20 s","Sauts latéraux (sur une ligne) : 4 × 20 s","Squats sautés enchaînés : 4 × 8","Gainage planche dynamique : 3 × 40 s"],
    conseil:"Le contact au sol doit être le plus court possible. Imagine un sol brûlant. Cette réactivité fait la différence dans les changements de rythme." },
  jeudi:{ titre:"Départ + relance", focus:"Enchaîner explosion et maintien",
    exos:["Sprint 10 m depuis position d'attaque : 6 × (récup complète)","Squat saut + sprint 5 m : 5 essais","Pompes explosives : 4 × 8","Hollow rock : 3 × 25"],
    conseil:"En compétition, le départ ne suffit pas : il faut tenir la vitesse ensuite. On enchaîne explosion puis relance pour habituer ton corps à ne pas relâcher." } },

{ s:10, phase:"Construction", titre:"Séparer ta valeur de tes résultats",
  mental:{ titre:"Les 3 critères qui ne dépendent pas du score",
    pourquoi:"Si tu juges ta valeur sur ton résultat, tu seras malheureux la plupart du temps. Évalue-toi plutôt sur ce que tu contrôles : ton engagement, ta technique, ta gestion mentale.",
    consigne:"Définis 3 critères de « bonne performance » qui ne dépendent PAS du résultat. Exemple : « je me suis engagé d'entrée », « j'ai gardé mon calme avant de partir », « j'ai relancé après mon erreur ». Évalue-toi sur ces 3 critères après chaque session cette semaine.",
    declencheur:"Tu vas reprendre le pouvoir sur ta satisfaction. Une bonne performance devient possible même sans victoire — ce qui, paradoxalement, t'amène plus souvent à gagner." },
  lundi:{ titre:"Force unilatérale", focus:"Équilibrer les deux côtés",
    exos:["Squats bulgares : 4 × 10 par jambe","Montées sur banc explosives : 4 × 10 par jambe","Pompes diamant : 3 × 10","Gainage latéral dynamique : 3 × 12 par côté"],
    conseil:"Beaucoup d'athlètes ont un côté plus fort. Le travail unilatéral corrige ce déséquilibre — clé pour des appuis réguliers et puissants." },
  jeudi:{ titre:"Explosivité totale", focus:"Combiner haut et bas du corps",
    exos:["Burpees explosifs (saut haut) : 4 × 8","Squats sautés : 4 × 10","Pompes sautées (mains décollent) : 3 × 6","Hollow hold : 3 × 35 s"],
    conseil:"La performance engage tout le corps. Les burpees explosifs entraînent la coordination globale entre le haut et le bas." } },

{ s:11, phase:"Construction", titre:"Tenir le niveau sous fatigue",
  mental:{ titre:"Le focus sur le processus",
    pourquoi:"Quand la fatigue arrive en fin d'effort, ton cerveau veut penser au résultat. C'est exactement ce qui te fait craquer. Le remède : ramener ton attention sur UNE action concrète.",
    consigne:"Cette semaine, sur tes séances les plus dures, quand la fatigue monte, fixe ton attention sur une seule chose technique (« pieds rapides », « regard loin », « tronc gainé »). Pas le chrono, pas la fin. Juste l'action présente.",
    declencheur:"Tu vas découvrir que la fatigue mentale vient surtout des pensées de résultat. En te concentrant sur le geste, tu tiens beaucoup plus longtemps." },
  lundi:{ titre:"Endurance de force", focus:"Tenir la puissance dans la durée",
    exos:["Circuit 4 tours : 15 squats + 10 fentes/jambe + 30 s gainage","Repos 60 s entre tours","Finition : 3 × 20 squats sautés"],
    conseil:"On ajoute du volume pour préparer la capacité à répéter l'effort. Le but : être aussi fort à la fin qu'au début." },
  jeudi:{ titre:"Répétition de départs", focus:"Reproduire l'enchaînement des efforts",
    exos:["8 × sprint 10 m depuis position d'attaque, récup 60 s seulement","Squats sautés : 4 × 10","Gainage planche : 3 × 45 s"],
    conseil:"Récup courte volontairement : en compétition tu enchaînes les efforts avec peu de repos. On entraîne ton explosivité à rester intacte même fatigué." } },

{ s:12, phase:"Construction", titre:"Bilan & ancrage du bloc 2",
  mental:{ titre:"Visualisation de la performance complète",
    pourquoi:"Tu as travaillé le départ, le reset, l'engagement. Maintenant on assemble : visualise une performance entière, du début à la fin, en intégrant tous tes outils mentaux.",
    consigne:"3 fois cette semaine, 7 minutes : visualise une compétition complète. Le départ (ton rituel), l'explosion, une erreur (ton reset en 3 s), un engagement osé (ta décision), la fin franchie. Vis-la entièrement.",
    declencheur:"Tu programmes une performance parfaite dans ton système nerveux. Le jour J, ton corps suivra le chemin que tu auras tracé." },
  lundi:{ titre:"Test de puissance", focus:"Mesurer les gains du bloc 2",
    exos:["Saut en longueur sans élan : 5 essais (compare à la semaine 6)","Max squats sautés en 30 s : note le nombre","Circuit complet 3 tours","Gainage planche : note ton temps max"],
    conseil:"Note tous tes chiffres. Tu vas voir des progrès nets vs semaine 6. C'est la preuve concrète que tes points faibles deviennent forts." },
  jeudi:{ titre:"Départ chronométré", focus:"Évaluer ton explosion",
    exos:["6 × sprint 10 m depuis position d'attaque (fais-toi chronométrer si possible)","Note ton meilleur temps","Squats sautés : 4 × 10","Hollow hold : 3 × 40 s"],
    conseil:"Garde une trace de ton meilleur sprint. On le bat en semaine 18 et 24. L'explosivité au départ est une arme dans presque tous les sports." } },

// ─────────────────────────── BLOC 3 · PUISSANCE ───────────────────────────
{ s:13, phase:"Puissance", titre:"Maîtriser la pression de l'enjeu",
  mental:{ titre:"L'exposition graduée à la pression",
    pourquoi:"On ne gère pas la pression en l'évitant, mais en s'y habituant par petites doses. Tu vas créer volontairement de l'enjeu à l'entraînement pour que la compétition paraisse plus facile.",
    consigne:"Cette semaine, mets-toi sous pression artificielle : annonce à voix haute un objectif avant un exercice (« je fais 12 répétitions parfaites »), filme-toi, ou demande à quelqu'un de te regarder. Apprends à performer SOUS le regard.",
    declencheur:"Plus tu t'exposes à de la pression choisie, moins la pression subie te fait peur. Tu inverses le rapport de force." },
  lundi:{ titre:"Force explosive lourde", focus:"Le maximum de puissance par mouvement",
    exos:["Squats unijambe (pistol assisté) : 4 × 6 par jambe","Sauts sur surface haute (banc solide) : 4 × 6","Pompes explosives claquées si possible : 4 × 5","Gainage anti-rotation : 3 × 15 par côté"],
    conseil:"On cherche la puissance pure : peu de répétitions, intensité maximale, récup complète. Chaque effort doit être ton meilleur." },
  jeudi:{ titre:"Puissance d'accélération", focus:"Puissance sur les premiers mètres",
    exos:["Sprints 15 m départ arrêté : 6 × (récup 2 min)","Squat saut + sprint immédiat : 5 essais","Montées explosives banc : 4 × 8 par jambe","Hollow rock : 4 × 20"],
    conseil:"L'accélération initiale décide souvent l'issue. Ces sprints courts maximaux construisent la puissance qui te met devant dès le départ." } },

{ s:14, phase:"Puissance", titre:"La confiance inconditionnelle",
  mental:{ titre:"Les ancres de confiance",
    pourquoi:"Ta confiance doit tenir même après une mauvaise compétition. Pour ça, elle doit être ancrée sur des constantes que tu contrôles toujours : ton attitude, ton engagement, ton travail — jamais le résultat.",
    consigne:"Définis 2-3 constantes qui ne dépendent jamais du résultat : « je m'applique toujours », « je m'engage dans l'effort », « je reste correct dans l'adversité ». Chaque jour cette semaine, vérifie que tu les as respectées. Ta confiance s'ancre là.",
    declencheur:"Tu construis une confiance qui ne s'effondre plus, parce qu'elle ne dépend plus de variables que tu ne maîtrises pas." },
  lundi:{ titre:"Puissance & stabilité", focus:"Force utile en situation instable",
    exos:["Squats bulgares sautés : 4 × 8 par jambe","Gainage planche sur instabilité (pieds sur coussin/serviette roulée) : 4 × 30 s","Pompes lestées : 4 × 8","Pallof press : 3 × 12 par côté"],
    conseil:"En compétition, ta force doit s'exprimer en mouvement et en déséquilibre. On entraîne la puissance en condition instable, plus proche du réel." },
  jeudi:{ titre:"Sprints répétés", focus:"Puissance répétable",
    exos:["8 × sprint 15 m, récup 90 s","Squats sautés : 4 × 12","Skipping rapide : 4 × 20 s","Gainage : 3 × 45 s"],
    conseil:"On augmente le nombre de sprints. Objectif : que ton 8e sprint soit aussi puissant que le 1er. C'est ça, la régularité de champion." } },

{ s:15, phase:"Puissance", titre:"Attaquer la difficulté technique",
  mental:{ titre:"La visualisation des situations difficiles",
    pourquoi:"Les situations qui te font hésiter se débloquent d'abord dans la tête. En les visualisant réussies des dizaines de fois, tu enlèves la peur avant même d'y être confronté.",
    consigne:"Identifie LA situation qui te fait le plus hésiter dans ton sport. Cette semaine, visualise-la réussie 10 fois par jour, en détail : ton approche, ton geste, ta réussite. Puis, à l'entraînement, engage-la avec ton mot-ancre.",
    declencheur:"La situation qui te bloquait va devenir un endroit où tu gagnes. La peur cède quand le cerveau a déjà « vu » la réussite." },
  lundi:{ titre:"Détente verticale", focus:"Sauter plus haut, être plus explosif",
    exos:["Sauts verticaux max : 5 × 5","Sauts groupés : 4 × 8","Squats unijambe : 4 × 6 par jambe","Superman + hollow alternés : 3 × 30 s"],
    conseil:"La détente verticale sert dans énormément de gestes sportifs. Plus de détente = plus d'options pour faire la différence." },
  jeudi:{ titre:"Coordination & relance", focus:"Générer de la vitesse efficacement",
    exos:["Squats pulsés : 4 × 20","Sauts avant-arrière rapides : 4 × 20 s","Fentes sautées : 4 × 10","Gainage dynamique : 3 × 40 s"],
    conseil:"Produire de la vitesse efficacement repose sur des jambes qui poussent vite et fort. Ces squats pulsés entraînent exactement ce ressort." } },

{ s:16, phase:"Puissance", titre:"L'exigence juste",
  mental:{ titre:"Transformer l'exigence toxique",
    pourquoi:"Si tu te flagelles à chaque erreur, ton exigence te détruit au lieu de te tirer vers le haut. L'exigence juste vise le progrès, pas la perfection. Elle est ferme sur l'effort, douce sur le résultat.",
    consigne:"Cette semaine, à chaque fois que tu te critiques durement, reformule comme le ferait un bon coach : remplace « je suis nul » par « qu'est-ce que j'ajuste au prochain essai ? ». Note 3 fois où tu as réussi ce changement.",
    declencheur:"Tu vas découvrir que tu progresses PLUS vite en étant exigeant ET bienveillant. La dureté envers soi est un frein, pas un moteur." },
  lundi:{ titre:"Puissance maximale", focus:"Le pic de force du bloc",
    exos:["Pistol squats (ou assistés) : 4 × 6 par jambe","Sauts sur banc haut : 5 × 5","Pompes explosives : 4 × 6","Gainage planche lestée : 3 × 40 s"],
    conseil:"Tu es à mi-parcours du bloc puissance. Si les pistols viennent, c'est un excellent marqueur de force unilatérale — directement utile à tes appuis." },
  jeudi:{ titre:"Départ maximal", focus:"Explosion pure au signal",
    exos:["6 × sprint 10 m départ position d'attaque, intensité maximale, récup 2 min","Squat saut max : 5 × 5","Burpees explosifs : 3 × 8","Hollow hold : 3 × 45 s"],
    conseil:"Récup longue, intensité totale. On cherche le meilleur départ possible, pas l'endurance. Chaque départ doit être ta meilleure explosion." } },

{ s:17, phase:"Puissance", titre:"Gérer l'adversaire plus fort",
  mental:{ titre:"Faire sa propre compétition",
    pourquoi:"Quand un adversaire plus fort est à côté de toi, ton cerveau veut le surveiller — et tu perds le focus sur TA performance. Le remède : ramener toute ton attention sur ton plan, comme s'il n'existait pas.",
    consigne:"Cette semaine, à chaque exercice, fixe-toi sur TON exécution sans te comparer à personne. Si tu t'entraînes avec d'autres, entraîne-toi à ne PAS les regarder, à rester dans ta bulle. Note quand tu y arrives.",
    declencheur:"Tu vas réaliser que tes meilleures performances arrivent quand tu oublies les autres. La comparaison vole ton énergie ; le focus la concentre." },
  lundi:{ titre:"Force-vitesse", focus:"Convertir la force en vitesse",
    exos:["Squats sautés lestés léger : 4 × 8","Fentes sautées explosives : 4 × 8 par jambe","Sauts horizontaux enchaînés : 4 × 6","Gainage latéral : 3 × 40 s par côté"],
    conseil:"On lie la force construite à la vitesse d'exécution. Ce qui compte n'est pas juste d'être fort, mais d'être fort VITE." },
  jeudi:{ titre:"Endurance de sprint", focus:"Tenir la puissance sur la durée",
    exos:["10 × sprint 12 m, récup 75 s","Squats sautés : 4 × 12","Mountain climbers : 4 × 30 s","Gainage : 3 × 50 s"],
    conseil:"On monte à 10 sprints. La fatigue va venir — c'est le but. Apprends à garder une bonne technique même quand ça pique." } },

{ s:18, phase:"Puissance", titre:"Bilan & ancrage du bloc 3",
  mental:{ titre:"Visualisation sous pression maximale",
    pourquoi:"On combine tout : tu vas visualiser ta compétition la plus importante, avec le maximum d'enjeu, en restant maître de tes émotions grâce à tous tes outils.",
    consigne:"3 fois cette semaine, 8 minutes : visualise TA compétition objectif de la saison. Le contexte (le public, l'enjeu), tes émotions, ton rituel, ton départ explosif, ta gestion de la pression, ta performance propre. Termine toujours par la réussite.",
    declencheur:"Tu rends familière la situation la plus stressante. Le jour réel, ton cerveau pensera « je connais déjà ça » — et tu seras calme là où les autres craquent." },
  lundi:{ titre:"Test de puissance", focus:"Mesurer les gains du bloc 3",
    exos:["Saut en longueur sans élan : 5 essais (compare semaines 6 & 12)","Saut vertical max : note la hauteur","Max pistols par jambe : note le nombre","Gainage planche max : note le temps"],
    conseil:"Tu devrais battre tes scores des bilans précédents. Ces chiffres sont la preuve que ton corps d'athlète se transforme." },
  jeudi:{ titre:"Départ chronométré", focus:"Battre ton record",
    exos:["6 × sprint 10 m chronométrés depuis position d'attaque","Compare à ton temps de la semaine 12","Squats sautés : 4 × 10","Hollow hold : 3 × 45 s"],
    conseil:"Bats ton départ de la semaine 12. Tu vas le voir : ce qui te coûtait au départ devient ton point d'attaque." } },

// ─────────────────────────── BLOC 4 · PERFORMANCE ───────────────────────────
{ s:19, phase:"Performance", titre:"Transférer en compétition",
  mental:{ titre:"Les objectifs de processus en compétition",
    pourquoi:"Le jour de la compétition, tu ne dois penser ni au résultat, ni à la technique abstraite — mais à 1 ou 2 objectifs concrets de jeu. Ça donne un but qui ne dépend pas du score et libère ton naturel.",
    consigne:"Pour ta prochaine session-compétition cette semaine, choisis 1 ou 2 objectifs de processus uniquement (ex : « je m'engage d'entrée », « je tiens mon intensité jusqu'au bout »). Concentre-toi UNIQUEMENT dessus. Évalue-les après.",
    declencheur:"Tu vas sentir une libération : avec un focus de processus, ton corps fait ce qu'il sait faire au lieu d'être paralysé par l'enjeu." },
  lundi:{ titre:"Puissance spécifique", focus:"Reproduire les efforts de compétition",
    exos:["Sprint 15 m + changement de direction : 6 essais","Squats sautés : 4 × 10","Fentes sautées : 4 × 8 par jambe","Gainage anti-rotation : 3 × 15 par côté"],
    conseil:"On rapproche le travail de la réalité : explosion + changement de direction, comme dans la plupart des situations de compétition." },
  jeudi:{ titre:"Enchaînement compétition", focus:"Simuler un effort complet",
    exos:["Circuit : sprint 10 m + 5 squats sautés + sprint 10 m, 6 tours, récup 90 s","Pompes explosives : 4 × 6","Hollow rock : 4 × 20"],
    conseil:"Ce circuit imite la structure d'un effort de compétition : explosion, relances, maintien. Ton corps apprend l'enchaînement réel." } },

{ s:20, phase:"Performance", titre:"Le pic de concentration",
  mental:{ titre:"Le recentrage entre les efforts",
    pourquoi:"En compétition, tu enchaînes souvent plusieurs efforts en peu de temps. Entre chaque, tu dois pouvoir te recentrer en 20 secondes pour repartir neuf, sans traîner l'émotion du précédent.",
    consigne:"Crée ton protocole de recentrage en 20 s : 3 respirations lentes, ton mot-ancre, regard fixé sur un point. Répète-le cette semaine entre chaque série d'exercices, jusqu'à ce qu'il soit fluide et automatique.",
    declencheur:"Le jour de la compétition, entre tes efforts, tu auras un outil pour repartir à 100 % à chaque fois — là où les autres restent bloqués sur le précédent." },
  lundi:{ titre:"Affûtage puissance", focus:"Maintenir la puissance, réduire le volume",
    exos:["Squats sautés max : 4 × 6","Sauts sur banc : 4 × 5","Sprints 10 m : 5 × (récup complète)","Gainage : 3 × 40 s"],
    conseil:"On entre en phase d'affûtage : moins de volume, intensité maintenue. Le but est d'arriver frais et explosif, pas épuisé." },
  jeudi:{ titre:"Vitesse pure", focus:"Le système nerveux à pleine vitesse",
    exos:["Skipping ultra-rapide : 6 × 10 s","Squats sautés rapides : 4 × 8","Départs explosifs 5 m : 6 × (récup 90 s)","Hollow hold : 3 × 40 s"],
    conseil:"Efforts courts et explosifs uniquement. On garde le système nerveux vif et rapide, sans accumuler de fatigue." } },

{ s:21, phase:"Performance", titre:"La routine du jour J",
  mental:{ titre:"Finaliser ton protocole de compétition",
    pourquoi:"Le jour J ne s'improvise pas. Tu dois avoir une routine complète, de ton réveil jusqu'au départ, qui te met dans le meilleur état possible sans que tu aies à réfléchir.",
    consigne:"Écris ta routine complète du jour de compétition : heure de réveil, petit-déjeuner, échauffement, séquence pré-effort, gestion entre les efforts. Teste-la lors de ta prochaine session pour l'ajuster. Affine-la.",
    declencheur:"Une routine rodée enlève l'incertitude. Le jour J, tu n'as plus qu'à dérouler — ton énergie va à la performance, pas à la gestion du stress." },
  lundi:{ titre:"Puissance fraîche", focus:"Qualité maximale, fatigue minimale",
    exos:["Sprints 12 m : 5 × (récup 2 min)","Squats sautés : 3 × 6","Pompes explosives : 3 × 6","Gainage : 2 × 40 s"],
    conseil:"Volume réduit, intensité haute. Tu dois finir la séance avec l'impression d'en avoir encore sous le pied. C'est voulu." },
  jeudi:{ titre:"Activation", focus:"Réveiller le corps sans le fatiguer",
    exos:["Skipping rapide : 4 × 10 s","Squats sautés : 3 × 6","Départs 5 m : 4 × (récup complète)","Mobilité + gainage léger : 2 × 30 s"],
    conseil:"Séance courte d'activation. On garde le système explosif allumé tout en restant frais pour la performance." } },

{ s:22, phase:"Performance", titre:"L'état de flow",
  mental:{ titre:"Retrouver le plaisir du geste",
    pourquoi:"Tes meilleures performances arrivent quand tu es dans le flow : concentré mais détendu, performant sans forcer. Cet état vient du plaisir, pas de la contrainte. On le cultive volontairement.",
    consigne:"Cette semaine, fais au moins une session avec une seule règle : aucun objectif de performance, juste le plaisir du mouvement. Reconnecte avec POURQUOI tu fais ce sport. Note ce que tu ressens.",
    declencheur:"Tu vas te rappeler que tu performes mieux quand tu prends du plaisir. Le flow n'est pas un luxe — c'est ton état de performance maximale." },
  lundi:{ titre:"Puissance ludique", focus:"Performer en s'amusant",
    exos:["Parcours libre de sauts et sprints (invente-le) : 15 min","Squats sautés : 3 × 8","Gainage : 2 × 40 s"],
    conseil:"Transforme la séance en jeu. Le corps apprend mieux dans le plaisir — et c'est exactement l'état que tu veux retrouver en compétition." },
  jeudi:{ titre:"Vitesse plaisir", focus:"Explosivité sans pression",
    exos:["Départs explosifs en te chronométrant pour le fun : 6 essais","Skipping rapide : 4 × 10 s","Sauts variés : 3 × 8","Hollow hold : 2 × 40 s"],
    conseil:"Joue avec ta vitesse, cherche à battre ton propre record en souriant. Le plaisir et la performance vont ensemble, jamais l'un contre l'autre." } },

{ s:23, phase:"Performance", titre:"Préparer le pic de forme",
  mental:{ titre:"La visualisation finale intégrée",
    pourquoi:"Tu as tous les outils. Cette semaine, on les assemble en une visualisation parfaite, répétée, qui programme ta meilleure performance possible dans les moindres détails.",
    consigne:"Chaque jour cette semaine, 8 minutes : visualise ta performance parfaite du début à la fin, en intégrant TOUT : routine, rituel, départ explosif, gestion de pression, performance propre, recentrage entre les efforts, plaisir, fin franchie. Vis-la, ne la regarde pas.",
    declencheur:"Tu auras répété ta performance idéale des dizaines de fois mentalement. Le jour J, ce sera comme la refaire — ton corps connaîtra déjà le chemin." },
  lundi:{ titre:"Affûtage final", focus:"Fraîcheur et explosivité",
    exos:["Sprints 10 m : 4 × (récup complète)","Squats sautés : 3 × 5","Pompes explosives : 2 × 5","Gainage : 2 × 30 s"],
    conseil:"Très peu de volume. Tu prépares ton corps à exprimer son maximum. Reposé + explosif = pic de forme." },
  jeudi:{ titre:"Dernière activation", focus:"Allumer la mèche",
    exos:["Skipping rapide : 3 × 10 s","Départs 5 m : 4 × (récup complète)","Squats sautés : 2 × 5","Mobilité légère"],
    conseil:"Séance ultra-courte. Le travail est fait. On garde juste le système nerveux vif et prêt à exploser." } },

{ s:24, phase:"Performance", titre:"Performer — et faire le bilan",
  mental:{ titre:"Le débrief de progression",
    pourquoi:"24 semaines de travail méritent d'être mesurées. Regarder le chemin parcouru ancre ta confiance dans des preuves solides — et trace ta suite.",
    consigne:"Relis ton carnet de preuves (semaine 4) et tes bilans physiques (semaines 6, 12, 18). Écris : 3 points forts que tu as consolidés, 2 points faibles que tu as corrigés, et ton prochain objectif. Partage-le avec Fabien via la messagerie.",
    declencheur:"Tu vas mesurer noir sur blanc ta transformation. Cette preuve de progression est la fondation de toute ta confiance future." },
  lundi:{ titre:"Test final complet", focus:"Mesurer 24 semaines de transformation",
    exos:["Saut en longueur sans élan : compare aux semaines 6, 12, 18","Saut vertical max","Max pistols par jambe","Gainage planche max"],
    conseil:"Compare TOUS tes chiffres au départ. La progression que tu vois ici, c'est celle que tu mettras en compétition. Tu n'es plus le même athlète." },
  jeudi:{ titre:"Départ record", focus:"Ta meilleure explosion",
    exos:["6 × sprint 10 m chronométrés depuis position d'attaque","Bats ton record des semaines 12 et 18","Célèbre le travail accompli","Gainage : 3 × 45 s"],
    conseil:"Ton dernier départ du programme. Donne tout. Puis regarde le chemin : de la semaine 1 à aujourd'hui, tu as construit un vrai athlète. La suite t'appartient." } },
];
